# action.yml
name: 'action-rsync'
description: 'rsync actions'
inputs:
  src:
    description: 'source'
    required: true
  dest:
    description: 'destination'
    required: true
  options:
    description: 'rsync options'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.src }}
    - ${{ inputs.dest }}
    - ${{ inputs.options }}
