# action.yml
name: 'action-rsync'
description: 'rsync actions'
inputs:
  src:
    description: 'source'
    required: true
  dest:
    description: 'destination e.g ssh-user@ssh-host:/path'
    required: true
  options:
    description: 'rsync options'
    default: -aP
  ssh_key:
    description: 'ssh private key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
